app = "remove-bg-api"  # You can change this to a unique name

primary_region = "sin"  # Singapore, or change to your preferred region (like bom, lax, etc.)

[build]
  image = "python:3.11-slim"  # Use slim image for smaller size

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 0
